sequenceDiagram
    Resolvers       ->>+ Code Intel API: FindClosestDumps
    Code Intel API  ->>+ Store: FindClosestDumps
    Store          -->>- Code Intel API: [dump 1, ...]
    Code Intel API -->>- Resolvers: [dump 1, ...]

    loop for each dump returning first result
        Resolvers       ->>+ Code Intel API: Definitions(dump 1, pos)
        Code Intel API  ->>+ Bundle Manager: Definitions(dump 1, pos)
        Bundle Manager -->>- Code Intel API: definitions
        opt if not empty
            Code Intel API -->> Resolvers: definitions
        end

        Code Intel API  ->>+ Bundle Manager: MonikersByPosition(dump 1, pos)
        Bundle Manager -->>- Code Intel API: [moniker 1, ...]

        loop for each moniker returning first result
            Code Intel API  ->>+ Bundle Manager: PackageInformation(moniker 1)
            Bundle Manager -->>- Code Intel API: pkg
            Code Intel API  ->>+ Store: GetPackage(pkg)
            Store          -->>- Code Intel API: dump 2
            Code Intel API  ->>+ Bundle Manager: MonikerResults(dump 2, moniker 1)
            Bundle Manager  ->>- Code Intel API: definitions
        end
        opt if not empty
            Code Intel API -->>- Resolvers: definitions
        end
    end
