sequenceDiagram
    Resolvers       ->>+ Code Intel API: FindClosestDumps
    Code Intel API  ->>+ Store: FindClosestDumps
    Store          -->>- Code Intel API: [dump 1, ...]
    Code Intel API -->>- Resolvers: [dump 1, ...]

    loop for each dump returning first result
        Resolvers       ->>+ Code Intel API: Hover(dump 1, pos)
        Code Intel API  ->>+ Bundle Manager: Hover(dump 1, pos)
        Bundle Manager -->>- Code Intel API: hover text
        opt if not empty
            Code Intel API -->> Resolvers: hover text
        end

        Code Intel API  ->>  Code Intel API: Definition(dump 1, pos)
        Code Intel API  ->>+ Bundle Manager: Hover(definition dump, definition pos)
        Bundle Manager -->>- Code Intel API: hover text

        opt if not empty
            Code Intel API -->>- Resolvers: hover text
        end
    end
