sequenceDiagram
    Resolvers       ->>+ Code Intel API: FindClosestDumps
    Code Intel API  ->>+ Store: FindClosestDumps
    Store          -->>- Code Intel API: [dump 1, ...]
    Code Intel API -->>- Resolvers: [dump 1, ...]

    loop for each dump
        Resolvers ->>+ Code Intel API: References(cursor)

        alt
            Code Intel API           ->>+ Reference Page Resolver: handleSameDumpCursor
            Reference Page Resolver  ->>+ Bundle Manager: References
            Bundle Manager          -->>- Reference Page Resolver: references
            Reference Page Resolver -->>- Code Intel API: references, new cursor
        end

        alt
            Code Intel API           ->>+ Reference Page Resolver: handleSameDumpMonikersCursor
            Reference Page Resolver  ->>+ Bundle Manager: References
            Bundle Manager          -->>- Reference Page Resolver: references
            Reference Page Resolver  ->>+ Bundle Manager: MonikerResults
            Bundle Manager          -->>- Reference Page Resolver: references2
            Reference Page Resolver -->>- Code Intel API: (references2 - references1), new cursor
        end

        alt
            Code Intel API ->>+ Reference Page Resolver: handleDefinitionMonikersCursor
            loop for each moniker, returning first moniker with package data
                Reference Page Resolver ->>+ Bundle Manager: PackageInformation
                Bundle Manager         -->>- Reference Page Resolver: pdata
                Reference Page Resolver ->>+ Store: GetPackage(pkg)
                Store                  -->>- Reference Page Resolver: dump 2
                Reference Page Resolver ->>+ Bundle Manager: MonikerResults(dump 2, moniker 1)
                Bundle Manager          ->>- Reference Page Resolver: references
            end
            Reference Page Resolver -->>- Code Intel API: references, new cursor
        end

        alt
            Code Intel API          ->>+ Reference Page Resolver: handleSameRepoCursor
            Reference Page Resolver ->>+ Store: SameRepoPager
            Store                  -->>- Reference Page Resolver: dumps
            loop for each dump
                Reference Page Resolver ->>+ Bundle Manager: MonikerResults(dump, moniker from above)
                Bundle Manager         -->>- Reference Page Resolver: references
            end
            Reference Page Resolver -->>- Code Intel API: references, new cursor
        end

        alt
            Code Intel API          ->>+ Reference Page Resolver: handleRemoteRepoCursor
            Reference Page Resolver ->>+ Store: PackageReferencePager
            Store                  -->>- Reference Page Resolver: dumps
            loop for each dump
                Reference Page Resolver ->>+ Bundle Manager: MonikerResults(dump, moniker from above)
                Bundle Manager         -->>- Reference Page Resolver: references
            end
            Reference Page Resolver -->>- Code Intel API: references, new cursor
        end

        Code Intel API -->>- Resolvers: concatenated references
    end
